/**
 * Connector Presets – pre-configured MCP connector definitions
 * inspired by Claude Desktop's connector gallery.
 * These are remote MCP connectors hosted by each service.
 * Users select one, enter required env vars (API keys, tokens), and connect.
 */

export interface ConnectorEnvKey {
	key: string
	label: string
	required: boolean
	placeholder?: string
	secret?: boolean
}

export interface ConnectorPreset {
	id: string
	name: string
	description: string
	icon: string // emoji or image URL
	category: string
	mcpConfig: {
		type: 'stdio' | 'http'
		command?: string
		args?: string[]
		envKeys?: ConnectorEnvKey[]
		url?: string
	}
}

/**
 * All connectors from https://claude.com/connectors
 * Each connector is listed as a remote MCP HTTP endpoint.
 * Users should obtain the actual MCP URL from each provider's documentation.
 */
export const CONNECTOR_PRESETS: ConnectorPreset[] = [
	// ---- Page 1 ----
	{ id: '10x-genomics', name: '10x Genomics Cloud', description: 'Interact with 10x Genomics Cloud platform', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abd7406980b388be9ed4e_10x%20Genomics%20Cloud.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your 10x Genomics API Key', secret: true }] } },
	{ id: 'activecampaign', name: 'ActiveCampaign', description: 'Autonomous marketing to transform how you work', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6913f44f36966b0154800214_logo_activecampaign.svg', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your ActiveCampaign API Key', secret: true }] } },
	{ id: 'ahrefs', name: 'Ahrefs', description: 'SEO & AI search analytics', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d489e3a9d195da9e8d2e8_ahrefs-logo.svg', category: 'SEO', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Ahrefs API Key', secret: true }] } },
	{ id: 'aiera', name: 'Aiera', description: 'Live events, filings, company publications, and more', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abd9230df5f81ef095019_Aiera.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Aiera API Key', secret: true }] } },
	{ id: 'airops', name: 'AirOps', description: 'Craft content that wins AI search', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6973cbbab064adc3bdffb11e_logo-airops.svg', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your AirOps API Key', secret: true }] } },
	{ id: 'airwallex', name: 'Airwallex', description: 'Assist developers integrating with the Airwallex platform', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6977ee686ffe1cb730e94f07_Airwallex%20Mark%20-%20Colour%20-%20Square.png', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Airwallex API Key', secret: true }] } },
	{ id: 'amplitude', name: 'Amplitude', description: 'Give your teams powerful behavioral insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abdac9a60d37ccbb9f396_Amplitude.jpg', category: 'Analytics', mcpConfig: { type: 'http', url: 'https://mcp.amplitude.com', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Amplitude API Key', secret: true }] } },
	{ id: 'asana', name: 'Asana', description: 'Connect to Asana to coordinate tasks, projects, and goals', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abdda280622da0e174da2_Asana.jpg', category: 'Productivity', mcpConfig: { type: 'http', url: 'https://mcp.asana.com/v2/mcp', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Asana API Key', secret: true }] } },
	{ id: 'atlassian', name: 'Atlassian Rovo', description: 'Access Jira & Confluence from Claude', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abde7cfa24b799acf7fc9_Atlassian.jpg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Atlassian API Key', secret: true }] } },
	{ id: 'aura', name: 'Aura', description: 'Company intelligence & workforce analytics', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abdf0757d9241e42ce447_Aura.jpg', category: 'Analytics', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Aura API Key', secret: true }] } },
	{ id: 'aws-marketplace', name: 'AWS Marketplace', description: 'Discover, evaluate, and buy solutions for the cloud', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/692ddfcc3b71a55bb1993c71_amazon.jpg', category: 'Cloud', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your AWS API Key', secret: true }] } },
	{ id: 'benchling', name: 'Benchling', description: 'Connect to R&D data, source experiments, and notebooks', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abdfc622a31cabb4ed418_Benchling.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Benchling API Key', secret: true }] } },
	{ id: 'benevity', name: 'Benevity', description: 'Find and engage with verified nonprofits', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/692e4c057216b17022e9dc17_benevity.svg', category: 'Social', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Benevity API Key', secret: true }] } },
	{ id: 'bigdata', name: 'Bigdata.com', description: 'Access real-time financial data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6983d643ae1a792dcbdae54c_Bigdata.com.svg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Bigdata.com API Key', secret: true }] } },
	{ id: 'biorender', name: 'BioRender', description: 'Search for and use scientific templates and icons', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abe5cecad201acb193aa2_BioRender.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your BioRender API Key', secret: true }] } },
	{ id: 'biorxiv', name: 'bioRxiv', description: 'Access to bioRxiv and medRxiv preprint data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3f052f1932d948bc6d21_biorx.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'API Key (optional)', secret: true }] } },
	{ id: 'bitly', name: 'Bitly', description: 'Shorten links, generate QR Codes, and track performance', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6945bbe8b83f23c13a1fa551_bitly.svg', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Bitly API Key', secret: true }] } },
	{ id: 'blackbaud', name: 'Blackbaud', description: 'Search, explore, and query Blackbaud data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/692e4c2509be5a9236dcb73b_blackbaud.svg', category: 'Enterprise', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Blackbaud API Key', secret: true }] } },
	{ id: 'blockscout', name: 'Blockscout', description: 'Access and analyze blockchain data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69409abb57bdbb7a4d76fdda_blockscout.svg', category: 'Blockchain', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'API Key (optional)', secret: true }] } },
	{
		id: 'box', name: 'Box', description: 'Search, access and get insights on your Box content', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abe6914fb83099a240fa4_Box.jpg', category: 'Storage',
		mcpConfig: {
			type: 'stdio', command: 'npx', args: ['-y', '@anthropic-ai/box-mcp-server'],
			envKeys: [
				{ key: 'BOX_DEV_TOKEN', label: 'Developer Token', required: false, placeholder: 'Box Developer Token (expires in 60 min)', secret: true },
				{ key: 'BOX_JWT_BASE64', label: 'JWT Config (Base64)', required: false, placeholder: 'Base64-encoded JWT configuration', secret: true },
				{ key: 'BOX_USER_ID', label: 'Box User ID', required: false, placeholder: 'Box user ID for JWT auth' },
			],
		},
	},
	{ id: 'braze', name: 'Braze', description: 'Analyze trends and gather insights on Braze Campaigns and Canvases', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d3887ab6983e351f7707d_idcBI1GxVf_1769814142619.jpeg', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Braze API Key', secret: true }] } },
	{ id: 'candid', name: 'Candid', description: "Research nonprofits and funders using Candid's data", icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6921eaf57e1729586a4611fe_candid.jpg', category: 'Research', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Candid API Key', secret: true }] } },
	{ id: 'canva', name: 'Canva', description: 'Search, create, autofill, and export Canva designs from a prompt', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abe745ff5e30a03edd1cc_Canva%20MCP%20Server.jpg', category: 'Design', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Canva API Key', secret: true }] } },
	{ id: 'cdata', name: 'CData', description: 'Managed MCP platform for 350 sources', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bee897df1888970aa432_cdata.svg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your CData API Key', secret: true }] } },

	// ---- Page 2 ----
	{ id: 'chembl', name: 'ChEMBL', description: 'Access to the ChEMBL Database', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3f1ba62e131168eafdfd_chembl.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'chronograph', name: 'Chronograph', description: 'Interact with your Chronograph data directly in Claude', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abe95391c4c066b490cb0_Chronograph.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Chronograph API Key', secret: true }] } },
	{ id: 'circleback', name: 'Circleback', description: 'Search and access context from meetings', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696323e2a1aaf767a84b4ebc_circleback.svg', category: 'Productivity', mcpConfig: { type: 'http', url: 'https://app.circleback.ai/api/mcp', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Circleback API Key', secret: true }] } },
	{ id: 'clay', name: 'Clay', description: 'Find prospects. Research accounts. Personalize outreach', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69774464eaca3c68a1a04ce4_Clay.svg', category: 'Sales', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Clay API Key', secret: true }] } },
	{ id: 'clickup', name: 'ClickUp', description: 'Project management & collaboration for teams & agents', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69409a6f2b6cc54b2041f38c_clickup.svg', category: 'Productivity', mcpConfig: { type: 'http', url: 'https://mcp.clickup.com/mcp', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your ClickUp API Key', secret: true }] } },
	{ id: 'clinical-trials', name: 'Clinical Trials', description: 'Access ClinicalTrials.gov data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6963259b8df14c13e41f9015_clinical-trials.svg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'clockwise', name: 'Clockwise', description: 'Advanced scheduling and time management for work', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abea15b2e81afb9619d33_Clockwise.jpg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Clockwise API Key', secret: true }] } },
	{ id: 'close', name: 'Close', description: 'Securely connect Claude to your Close data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abeac92266bd43baf3e13_Close.jpg', category: 'CRM', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Close API Key', secret: true }] } },
	{ id: 'cloudflare', name: 'Cloudflare', description: 'Build applications with compute, storage, and AI', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abeb765f2d57005074b8f_Cloudflare%20Developer%20Platform.jpg', category: 'Cloud', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Cloudflare API Key', secret: true }] } },
	{ id: 'cloudinary', name: 'Cloudinary', description: 'Manage, transform and deliver your images & videos', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abec2b389536b0797f344_Cloudinary.jpg', category: 'Media', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Cloudinary API Key', secret: true }] } },
	{ id: 'cms-coverage', name: 'CMS Coverage', description: 'Access the CMS Coverage Database', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3e9e884bd175dbadbf06_cms.jpg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'consensus', name: 'Consensus', description: 'Explore scientific research', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69868c8886175b426660b5b8_consensus-logo.svg', category: 'Research', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'API Key (optional)', secret: true }] } },
	{ id: 'context7', name: 'Context7', description: 'Up-to-date docs for LLMs and AI code editors', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698690879ec0fe5a8ed0e319_context7-icon-green.png', category: 'Development', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'coupler-io', name: 'Coupler.io', description: 'Access business data from hundreds of sources', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abef0d363c9893d2b1511_coupler.jpg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Coupler.io API Key', secret: true }] } },
	{ id: 'crossbeam', name: 'Crossbeam', description: 'Explore partner data and ecosystem insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6913f587fda5ed6a14574a0a_crossbeam.svg', category: 'Sales', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Crossbeam API Key', secret: true }] } },
	{ id: 'crypto-com', name: 'Crypto.com', description: 'Real time prices, orders, charts, and more for crypto', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bf961a7c4a6c6b6de7ff_crypto.com.svg', category: 'Blockchain', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'API Key (optional)', secret: true }] } },
	{ id: 'daloopa', name: 'Daloopa', description: 'Financial fundamental data and KPIs with hyperlinks', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf04280622da0e1773b0_Daloopa.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Daloopa API Key', secret: true }] } },
	{ id: 'databricks', name: 'Databricks', description: 'Managed MCP servers with Unity Catalog and Mosaic AI', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf0efc7c6c19c9ec062d_Databricks.jpg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Databricks API Key', secret: true }] } },
	{ id: 'devrev', name: 'DevRev', description: "Search and update your company's knowledge graph", icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69797d31d1e2debf8a87f5a7_DevRev_logo_2.svg', category: 'Development', mcpConfig: { type: 'http', url: 'https://api.devrev.ai/mcp/v1', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your DevRev API Key', secret: true }] } },
	{ id: 'dice', name: 'Dice', description: 'Find active tech jobs on Dice', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696ed95ff04fa48923f3fa49_dice_squarelogo.svg', category: 'Jobs', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'egnyte', name: 'Egnyte', description: 'Securely access and analyze Egnyte content', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf27902ed1e055163fd7_Egnyte.jpg', category: 'Storage', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Egnyte API Key', secret: true }] } },
	{ id: 'excalidraw', name: 'Excalidraw', description: 'MCP for creating interactive hand-drawn diagrams', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698b6d382644a53ecb859c9b_idJpJtW9KY_logos.png', category: 'Design', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'fellow-ai', name: 'Fellow.ai', description: 'Chat with your meetings to uncover actionable insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bec73a155fccfdab98ae_fellow.ai.svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Fellow.ai API Key', secret: true }] } },
	{ id: 'figma', name: 'Figma', description: 'Generate diagrams and better code from Figma context', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf35eff31cb9416d9ec4_Figma.jpg', category: 'Design', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Figma API Key', secret: true }] } },

	// ---- Page 3 ----
	{ id: 'fireflies', name: 'Fireflies', description: 'Analyze and generate insights from meeting transcripts', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf5cf91d777702ff2e6a_Fireflies.jpg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Fireflies API Key', secret: true }] } },
	{ id: 'function', name: 'Function (beta)', description: 'View lab test results summaries, get nutrition plans', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696146b3ef7f8280dc6a91ff_function-health.jpg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Function API Key', secret: true }] } },
	{ id: 'gamma', name: 'Gamma', description: 'Create presentations, docs, socials, and sites with AI', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6972b2009201ad5676779ae6_gamma.png', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Gamma API Key', secret: true }] } },
	{ id: 'glean', name: 'Glean', description: 'Bring enterprise context to Claude and your AI tools', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696e96ce46080bb76b08f5d6_glean-logo.svg', category: 'Enterprise', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Glean API Key', secret: true }] } },
	{ id: 'godaddy', name: 'GoDaddy', description: 'Search domains and check availability', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bf645c7a7cc8f935d96b_godaddy%20(1).svg', category: 'Web', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your GoDaddy API Key', secret: true }] } },
	{ id: 'bigquery', name: 'Google Cloud BigQuery', description: 'BigQuery: Advanced analytical insights for agents', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69825fde71dbb2043676fc68_brandmark-logo-google-bigquery.svg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Google Cloud API Key', secret: true }] } },
	{ id: 'google-compute-engine', name: 'Google Compute Engine', description: 'MCP server for Google Compute Engine', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6921e7cdccfb4d1db46251e1_google.jpg', category: 'Cloud', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your GCE API Key', secret: true }] } },
	{ id: 'granola', name: 'Granola', description: 'The AI notepad for meetings', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6983856f3c47bff2ec615f86_logo-square.svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Granola API Key', secret: true }] } },
	{ id: 'guru', name: 'Guru', description: 'Search and interact with your company knowledge', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6973fef9099795a074827034_1_Guru-G_Logo.svg', category: 'Enterprise', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Guru API Key', secret: true }] } },
	{ id: 'harmonic', name: 'Harmonic', description: 'Discover, research, and enrich companies and people', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d4a1ac4c3c5105f7dc970_harmonic.png', category: 'Sales', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Harmonic API Key', secret: true }] } },
	{ id: 'healthex', name: 'HealthEx (beta)', description: 'Connect your health records for personalized insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3e7cb91804401037ccb4_healthEx.jpg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your HealthEx API Key', secret: true }] } },
	{ id: 'hex', name: 'Hex', description: 'Answer questions with the Hex agent', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf6c6461f0fd29c63e59_Hex.jpg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Hex API Key', secret: true }] } },
	{ id: 'honeycomb', name: 'Honeycomb', description: 'Query and explore observability data and SLOs', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bf27e6d9dd347e34ca26_honeycomb.svg', category: 'DevOps', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Honeycomb API Key', secret: true }] } },
	{ id: 'hubspot', name: 'HubSpot', description: 'Chat with your CRM data to get personalized insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf89f91d777702ff37af_HubSpot.jpg', category: 'CRM', mcpConfig: { type: 'http', url: 'https://mcp.hubspot.com/mcp', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your HubSpot API Key', secret: true }] } },
	{ id: 'hugging-face', name: 'Hugging Face', description: 'Access the HF Hub and thousands of Gradio Apps', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abf96bd16a291db21b1ab_Hugging%20Face.jpg', category: 'AI', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'Your HF API Key', secret: true }] } },
	{ id: 'icd-10-codes', name: 'ICD-10 Codes', description: 'Access ICD-10-CM and ICD-10-PCS code sets', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3eb9f2f34ada6ce08e57_ICD-10.jpg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'indeed', name: 'Indeed', description: 'Search for jobs on Indeed', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfa1fc7c6c19c9ec2465_Indeed.jpg', category: 'Jobs', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'intercom', name: 'Intercom', description: 'AI access to Intercom data for better customer insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfac1647ce192e81c3ba_Intercom.jpg', category: 'CRM', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Intercom API Key', secret: true }] } },
	{ id: 'invideo', name: 'Invideo', description: 'Create videos with AI', icon: 'https://cdn.prod.website-files.com/plugins/Basic/assets/placeholder.60f9b1840c.svg', category: 'Media', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Invideo API Key', secret: true }] } },
	{ id: 'jam', name: 'Jam', description: 'Record screen and collect automatic context for issues', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfb928bf214f7824247c_Jam.jpg', category: 'Development', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Jam API Key', secret: true }] } },
	{ id: 'jotform', name: 'Jotform', description: 'Create forms & analyze submissions inside Claude', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfc71647ce192e81d28a_jotform.jpg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Jotform API Key', secret: true }] } },
	{ id: 'kiwi-com', name: 'Kiwi.com', description: 'Search flights in Claude', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6923bf058e26b5aa3c809b42_kiwi.svg', category: 'Travel', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'klaviyo', name: 'Klaviyo', description: 'Report, strategize & create with real-time Klaviyo data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69710feadd4fbcdc9202b732_klaviyo-poppy%20(1).png', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Klaviyo API Key', secret: true }] } },
	{ id: 'lastminute-com', name: 'lastminute.com', description: 'Search, compare and book flights across global airlines', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69701c118e725e7149be2b2f_logo_lastminute.com_vertical_positive.svg', category: 'Travel', mcpConfig: { type: 'http', envKeys: [] } },

	// ---- Page 4 ----
	{ id: 'learning-commons', name: 'Learning Commons Knowledge Graph', description: 'K-12 standards, skills, and learning progressions', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abfe0db0d82b0112d1531_1758567129415.jpeg', category: 'Education', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'lilt', name: 'LILT', description: 'High-quality translation with human verification', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d13e9fb2d1120753661ed_Lilt-LogoMark_Color.png', category: 'Translation', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your LILT API Key', secret: true }] } },
	{ id: 'linear', name: 'Linear', description: 'Manage issues, projects & team workflows in Linear', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690abff72b804fad37465165_Linear.jpg', category: 'Productivity', mcpConfig: { type: 'http', url: 'https://mcp.linear.app/mcp', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Linear API Key', secret: true }] } },
	{ id: 'lseg', name: 'LSEG', description: 'Access best in class data & analytics across asset classes', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac002ca8cf24dae1dfbe8_LSEG.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your LSEG API Key', secret: true }] } },
	{ id: 'lumin', name: 'Lumin', description: 'Manage documents, send signature requests, and convert Markdown to PDF', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69843e996011391070f38a40_lumin%20(1).svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Lumin API Key', secret: true }] } },
	{ id: 'lunarcrush', name: 'LunarCrush', description: 'Add real-time social media data to your searches', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697011202bc68d8b21660503_lunarcrush.png', category: 'Social', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your LunarCrush API Key', secret: true }] } },
	{ id: 'magic-patterns', name: 'Magic Patterns', description: 'Discuss and iterate on Magic Patterns designs', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6983b706c57aa5fd1fd7a2d2_magicpatterns.jpeg', category: 'Design', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Magic Patterns API Key', secret: true }] } },
	{ id: 'make', name: 'Make', description: 'Run Make scenarios and manage your Make account', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d14371cf45af84e39a93e_Make-Icon-Square-Purple.svg', category: 'Automation', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Make API Key', secret: true }] } },
	{ id: 'medidata', name: 'Medidata', description: 'Medidata provides clinical trial software solutions', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6963241073e3facf8ccc4053_medidata.svg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Medidata API Key', secret: true }] } },
	{ id: 'melon', name: 'Melon', description: 'Browse music charts & your personalized music picks', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac015d363c9893d2b3b46_Melon.jpg', category: 'Entertainment', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'Your Melon API Key', secret: true }] } },
	{ id: 'mercury', name: 'Mercury', description: 'Search, analyze and understand your finances on Mercury', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69725f86a86e37636164b38e_mercury-bordered.svg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Mercury API Key', secret: true }] } },
	{ id: 'mermaid-chart', name: 'Mermaid Chart', description: 'Validates & renders Mermaid diagrams as PNG images', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac024622a31cabb4f22f9_Mermaid%20Chart.jpg', category: 'Design', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'API Key (optional)', secret: true }] } },
	{ id: 'microsoft-365', name: 'Microsoft 365', description: 'Access SharePoint, OneDrive, Outlook, and Teams context', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690c442881b2f70098a4491a_logo_microsoft.svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Microsoft 365 API Key', secret: true }] } },
	{ id: 'miro', name: 'Miro', description: 'Access and create new content on Miro boards', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/69825d400692311462b4a241_Miro_Miro_Icon_0.svg', category: 'Design', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Miro API Key', secret: true }] } },
	{ id: 'monday', name: 'Monday', description: 'Manage projects, boards, and workflows in monday.com', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6921e782b78ebbcbede151d0_monday.jpg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Monday API Key', secret: true }] } },
	{ id: 'moodys-analytics', name: "Moody's Analytics", description: 'Risk insights, analytics, and decision intelligence', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac04450f8882a1c470ad2_Moody%27s%20Analytics.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: "Your Moody's API Key", secret: true }] } },
	{ id: 'morningstar', name: 'Morningstar', description: 'Up-to-date investment and market insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac04d1d56f274313a74c8_Morningstar.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Morningstar API Key', secret: true }] } },
	{ id: 'motherduck', name: 'MotherDuck', description: 'Analyze your data with natural language', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6972aeacfd96f311a3714191_duck_feet_square.svg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your MotherDuck API Key', secret: true }] } },
	{ id: 'mt-newswires', name: 'MT Newswires', description: 'Trusted real-time global financial news provider', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac05e101530e7d9d53fde_MT%20Newswires.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your MT Newswires API Key', secret: true }] } },
	{ id: 'n8n', name: 'n8n', description: 'Access and run your n8n workflows', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6927759bae1867cbd42ffc1c_n8n.svg', category: 'Automation', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your n8n API Key', secret: true }] } },
	{ id: 'netlify', name: 'Netlify', description: 'Create, deploy, manage, and secure websites on Netlify', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac06ca62460beff2c64be_Netlify.jpg', category: 'Web', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Netlify API Key', secret: true }] } },
	{ id: 'notion', name: 'Notion', description: 'Connect your Notion workspace to search, update, and power workflows', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac085f91d777702ff6935_Notion%20MCP%20Directory%20Logo.svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Notion API Key', secret: true }] } },
	{ id: 'npi-registry', name: 'NPI Registry', description: 'Access US National Provider Identifier (NPI) Registry', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3ed486c00439706bad8d_npi.jpg', category: 'Healthcare', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'open-targets', name: 'Open Targets', description: 'Drug target discovery and prioritisation platform', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3f34a5d8bf093e154de4_open-targets.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [] } },

	// ---- Page 5 ----
	{ id: 'oracle-netsuite', name: 'Oracle NetSuite', description: 'Connect Claude to NetSuite data for analysis & insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0797fb7905db81f0c5f_NetSuite%20AI%20Connector%20for%20Claude.jpg', category: 'Enterprise', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your NetSuite API Key', secret: true }] } },
	{ id: 'owkin', name: 'Owkin', description: 'Interact with AI agents built for biology', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3ef5bcc23b924b6da7b7_OWKIN.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Owkin API Key', secret: true }] } },
	{ id: 'paypal', name: 'PayPal', description: 'Access PayPal payments platform', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac08f7113e7cbba88188e_PayPal%20MCP%20Server.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your PayPal API Key', secret: true }] } },
	{ id: 'pendo', name: 'Pendo', description: 'Connect to Pendo for product and user insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6940b23f3f26a47b390c0c99_pendo-1%20(1).svg', category: 'Analytics', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Pendo API Key', secret: true }] } },
	{ id: 'pigment', name: 'Pigment', description: 'Analyze business data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d4cb13ba105a718e5899a_PigmentIcon_Digital_Colors.png', category: 'Analytics', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Pigment API Key', secret: true }] } },
	{ id: 'pitchbook', name: 'PitchBook', description: 'PitchBook data, embedded in the way you work', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0a9ce745a3175e0bf75_PitchBook.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your PitchBook API Key', secret: true }] } },
	{ id: 'plaid', name: 'Plaid', description: 'Monitor, debug, and optimize your Plaid integration', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0b95f15547a984ac458_Plaid%20Developer%20Tools.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Plaid API Key', secret: true }] } },
	{ id: 'playmcp', name: 'PlayMCP', description: 'Connect and use PlayMCP servers in your toolbox', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6972a742be081eafd340061c_PlayMCP_favicon_500x500.png', category: 'Development', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your PlayMCP API Key', secret: true }] } },
	{ id: 'port-io', name: 'Port IO', description: 'Build and query your developer portal and trigger developer workflows', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698b91a222c41c1f4087160d_Port%20symbol_white_bg.jpg', category: 'Development', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Port IO API Key', secret: true }] } },
	{ id: 'pubmed', name: 'PubMed', description: 'Search biomedical literature from PubMed', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0d0062f6400d634c165_PubMed.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'ramp', name: 'Ramp', description: 'Search, access, and analyze your Ramp financial data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0e242323897e8eeb479_Ramp.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Ramp API Key', secret: true }] } },
	{ id: 'scholar-gateway', name: 'Scholar Gateway', description: 'Enhance responses with scholarly research and citations', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696af1b6440e8fa2af7e4ef7_scholarly-gateway.svg', category: 'Research', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'sentry', name: 'Sentry', description: 'Search, query, and debug errors intelligently', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac10642323897e8eebfdd_Sentry%20MCP.jpg', category: 'DevOps', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Sentry API Key', secret: true }] } },
	{ id: 'similarweb', name: 'Similarweb', description: 'Real time web, mobile app, and market data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d44c93b1b461da6f2d32b_ide0afd3w6_1769817151433.jpeg', category: 'Analytics', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Similarweb API Key', secret: true }] } },
	{ id: 'slack', name: 'Slack', description: 'Send messages, create canvases, and fetch Slack data!', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac11074040a8d303e83a5_Slack.jpg', category: 'Communication', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Slack API Key', secret: true }] } },
	{ id: 'smartsheet', name: 'Smartsheet', description: 'Analyze and manage Smartsheet data with Claude', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697bea45f7bb423e2320333e_Smartsheet_ids5IEP7cO_0.svg', category: 'Productivity', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Smartsheet API Key', secret: true }] } },
	{ id: 'snowflake', name: 'Snowflake', description: 'Retrieve both structured and unstructured data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac11852ad018a42303c93_Snowflake.jpg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Snowflake API Key', secret: true }] } },
	{ id: 'sp-global', name: 'S&P Global', description: 'Query a range of S&P Global datasets, like Financials', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac0ed02d4106f1281e6e2_S%26P%20Global.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your S&P Global API Key', secret: true }] } },
	{ id: 'square', name: 'Square', description: 'Search and manage transaction, merchant, and payment data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac122efac2533660b7814_Square%20MCP.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Square API Key', secret: true }] } },
	{ id: 'starburst', name: 'Starburst', description: 'Securely retrieve data from your federated data sources', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6983b7a66d99c6d365109dd7_starburst.svg', category: 'Data', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Starburst API Key', secret: true }] } },
	{ id: 'stripe', name: 'Stripe', description: 'Payment processing and financial infrastructure tools', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac12b69f1d226d230746c_Stripe.jpg', category: 'Finance', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Stripe API Key', secret: true }] } },
	{ id: 'stytch', name: 'Stytch', description: 'Manage your Stytch Project', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac136c2e9d81397a62c6d_Stytch.jpg', category: 'Auth', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Stytch API Key', secret: true }] } },
	{ id: 'supabase', name: 'Supabase', description: 'Manage databases, authentication, and storage', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697be34a6f8631fa5411e263_supabase-logo-icon.svg', category: 'Development', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Supabase API Key', secret: true }] } },
	{ id: 'supermetrics', name: 'Supermetrics', description: 'Analyze marketing performance across 200+ platforms', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698ce8b30c74f4d90c0fe1d5_supermetrics.svg', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Supermetrics API Key', secret: true }] } },

	// ---- Page 6 ----
	{ id: 'synapse', name: 'Synapse.org', description: 'Search and metadata tools for Synapse scientific data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac13f62f6fe3fff49fedb_Synapse.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: false, placeholder: 'Your Synapse API Key', secret: true }] } },
	{ id: 'ticket-tailor', name: 'Ticket Tailor', description: 'Event platform for managing tickets, orders & more', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac149c2dc363a0c9f35f1_Ticket%20Tailor.jpg', category: 'Events', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Ticket Tailor API Key', secret: true }] } },
	{ id: 'tool-universe', name: 'Tool Universe', description: 'AI scientists with 600+ scientific tools', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/695f3f4ec601a69ce6b1e175_tooluniverse.jpg', category: 'Science', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Tool Universe API Key', secret: true }] } },
	{ id: 'trivago', name: 'Trivago', description: 'Find your ideal hotel at the best price', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6913f573b5cf9a67fff78b2a_logo_trivago.svg', category: 'Travel', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'udemy-business', name: 'Udemy Business', description: 'Search and explore skill-building resources', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696ed8566d655f9fb5aaf3a1_Udemy%20MCP%20Directory%20Logo.svg', category: 'Education', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Udemy API Key', secret: true }] } },
	{ id: 'vercel', name: 'Vercel', description: 'Analyze, debug, and manage projects and deployments', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac166a0909415690fdb58_Vercel.jpg', category: 'Development', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Vercel API Key', secret: true }] } },
	{ id: 'vibe-prospecting', name: 'Vibe Prospecting', description: 'Find company & contact data', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697972974b1a41306ae210e9_favicon_claude_web.png', category: 'Sales', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Vibe API Key', secret: true }] } },
	{ id: 'visier', name: 'Visier', description: 'Find people, productivity and business impact insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6914c78e0da65e9753d33051_visier.png', category: 'Analytics', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Visier API Key', secret: true }] } },
	{ id: 'webflow', name: 'Webflow', description: 'Design pages, manage CMS content, and automate site tasks', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/6972b98bb9c8d247685d5867_Social_Square_Blue.svg', category: 'Web', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Webflow API Key', secret: true }] } },
	{ id: 'windsor-ai', name: 'Windsor.ai', description: 'Connect 325+ marketing, analytics and CRM data sources', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697034e4879b35571408299c_windsor_160px.png', category: 'Marketing', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Windsor.ai API Key', secret: true }] } },
	{ id: 'wix', name: 'Wix', description: 'Manage and build sites and apps on Wix', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/696ed33f296efad49cec4b60_5968770.png', category: 'Web', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Wix API Key', secret: true }] } },
	{ id: 'wordpress-com', name: 'WordPress.com', description: 'Secure AI access to manage your WordPress.com sites', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697d469f9210481c04a8b9fd_wp-com160.png', category: 'Web', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your WordPress API Key', secret: true }] } },
	{ id: 'workato', name: 'Workato', description: 'Automate workflows and connect your business apps', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac17bc2e9d81397a63732_Workato.jpg', category: 'Automation', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Workato API Key', secret: true }] } },
	{ id: 'wyndham-hotels', name: 'Wyndham Hotels and Resorts', description: 'Discover the right Wyndham Hotel for you, faster', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/697cf97c1f0c55c49363e9d7_whr_app_icon_160x160.jpg', category: 'Travel', mcpConfig: { type: 'http', envKeys: [] } },
	{ id: 'yardi-virtuoso', name: 'Yardi Virtuoso', description: 'Real-time Yardi data & insights', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/698a82b6a1d69ff7878e09a6_yardi.jpeg', category: 'Real Estate', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Yardi API Key', secret: true }] } },
	{ id: 'zapier', name: 'Zapier', description: 'Automate workflows across thousands of apps via conversation', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac18581a191dea79db82d_Zapier.jpg', category: 'Automation', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your Zapier API Key', secret: true }] } },
	{ id: 'zoominfo', name: 'ZoomInfo', description: 'Enrich contacts & accounts with GTM intelligence', icon: 'https://cdn.prod.website-files.com/68a44d4040f98a4adf2207b6/690ac18e80e00e4418bf54c8_ZoomInfo.jpg', category: 'Sales', mcpConfig: { type: 'http', envKeys: [{ key: 'API_KEY', label: 'API Key', required: true, placeholder: 'Your ZoomInfo API Key', secret: true }] } },
]
